#!/usr/bin/env bash

config=$1
if [[ -z "$config" ]]; then
  echo "usage: $0 <configuration file>"
  exit 1
fi
if [[ ! -f "$config" ]]; then
  echo "cannot read configuration file '$config'"
  exit 1
fi

# Generate yukibot-packages.nix
if [[ ! -f yukibot-packages.nix ]]; then
  ./gen-package-list.sh
fi

# Build
nix-build --no-out-link || exit 1

# Kill any existing session
function is_yukibot_running {
  tmux ls | grep "^yukibot:" &>/dev/null
}
if is_yukibot_running; then
  echo "found existing session, killing"
  tmux send-keys -tyukibot C-c
  sleep 1
  while is_yukibot_running; do
    echo "... waiting"
    sleep 1
  done
fi

# Start new session
tmux new-session -syukibot -d "nix-shell --command 'yukibot $config'"
